#!/bin/bash

set -e

cd $WORKSPACE_ROOT_DIR

source venv/bin/activate

if (( $# )) ; then
  TARGETS=( $@ )
else
  TARGETS=( . )
fi

echo "Code Quality Scans ..."

mypy "${TARGETS[@]}"

pyre incremental
